// Country to currency mapping for venue registration
// Maps country names/codes to their default currency

export const countryToCurrency: Record<string, string> = {
  // North America
  'United States': 'USD',
  'USA': 'USD',
  'US': 'USD',
  'Canada': 'CAD',
  'CA': 'CAD',
  'Mexico': 'MXN',
  'MX': 'MXN',
  
  // Europe
  'United Kingdom': 'GBP',
  'UK': 'GBP',
  'GB': 'GBP',
  'Germany': 'EUR',
  'DE': 'EUR',
  'France': 'EUR',
  'FR': 'EUR',
  'Italy': 'EUR',
  'IT': 'EUR',
  'Spain': 'EUR',
  'ES': 'EUR',
  'Portugal': 'EUR',
  'PT': 'EUR',
  'Netherlands': 'EUR',
  'NL': 'EUR',
  'Belgium': 'EUR',
  'BE': 'EUR',
  'Ireland': 'EUR',
  'IE': 'EUR',
  'Austria': 'EUR',
  'AT': 'EUR',
  'Greece': 'EUR',
  'GR': 'EUR',
  'Switzerland': 'CHF',
  'CH': 'CHF',
  'Sweden': 'SEK',
  'SE': 'SEK',
  'Norway': 'NOK',
  'NO': 'NOK',
  'Denmark': 'DKK',
  'DK': 'DKK',
  'Poland': 'PLN',
  'PL': 'PLN',
  'Czech Republic': 'CZK',
  'CZ': 'CZK',
  'Hungary': 'HUF',
  'HU': 'HUF',
  'Romania': 'RON',
  'RO': 'RON',
  
  // Asia Pacific
  'Australia': 'AUD',
  'AU': 'AUD',
  'New Zealand': 'NZD',
  'NZ': 'NZD',
  'Japan': 'JPY',
  'JP': 'JPY',
  'China': 'CNY',
  'CN': 'CNY',
  'Hong Kong': 'HKD',
  'HK': 'HKD',
  'Singapore': 'SGD',
  'SG': 'SGD',
  'South Korea': 'KRW',
  'Korea': 'KRW',
  'KR': 'KRW',
  'India': 'INR',
  'IN': 'INR',
  'Thailand': 'THB',
  'TH': 'THB',
  'Malaysia': 'MYR',
  'MY': 'MYR',
  'Indonesia': 'IDR',
  'ID': 'IDR',
  'Philippines': 'PHP',
  'PH': 'PHP',
  'Vietnam': 'VND',
  'VN': 'VND',
  'Taiwan': 'TWD',
  'TW': 'TWD',
  
  // Middle East
  'United Arab Emirates': 'AED',
  'UAE': 'AED',
  'AE': 'AED',
  'Saudi Arabia': 'SAR',
  'SA': 'SAR',
  'Israel': 'ILS',
  'IL': 'ILS',
  'Qatar': 'QAR',
  'QA': 'QAR',
  'Kuwait': 'KWD',
  'KW': 'KWD',
  'Bahrain': 'BHD',
  'BH': 'BHD',
  'Oman': 'OMR',
  'OM': 'OMR',
  
  // Africa
  'South Africa': 'ZAR',
  'ZA': 'ZAR',
  'Nigeria': 'NGN',
  'NG': 'NGN',
  'Kenya': 'KES',
  'KE': 'KES',
  'Egypt': 'EGP',
  'EG': 'EGP',
  'Morocco': 'MAD',
  'MA': 'MAD',
  
  // South America
  'Brazil': 'BRL',
  'BR': 'BRL',
  'Argentina': 'ARS',
  'AR': 'ARS',
  'Chile': 'CLP',
  'CL': 'CLP',
  'Colombia': 'COP',
  'CO': 'COP',
  'Peru': 'PEN',
  'PE': 'PEN',
};

export const getCurrencyForCountry = (country: string): string => {
  // Try exact match first
  if (countryToCurrency[country]) {
    return countryToCurrency[country];
  }
  
  // Try case-insensitive match
  const normalizedCountry = country.trim();
  for (const [key, value] of Object.entries(countryToCurrency)) {
    if (key.toLowerCase() === normalizedCountry.toLowerCase()) {
      return value;
    }
  }
  
  // Default to USD if not found
  return 'USD';
};

export const currencySymbols: Record<string, string> = {
  'USD': '$',
  'EUR': '€',
  'GBP': '£',
  'AUD': 'A$',
  'CAD': 'C$',
  'JPY': '¥',
  'CNY': '¥',
  'INR': '₹',
  'CHF': 'Fr',
  'KRW': '₩',
  'SGD': 'S$',
  'HKD': 'HK$',
  'NZD': 'NZ$',
  'ZAR': 'R',
  'BRL': 'R$',
  'MXN': 'Mex$',
  'AED': 'د.إ',
  'SAR': '﷼',
  'THB': '฿',
  'MYR': 'RM',
  'PHP': '₱',
  'IDR': 'Rp',
  'VND': '₫',
};

// Comprehensive list of all countries with ISO codes
export const countries = [
  // Popular/Common first
  { name: 'Australia', code: 'AU' },
  { name: 'United States', code: 'US' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'Canada', code: 'CA' },
  { name: 'New Zealand', code: 'NZ' },
  // Alphabetical list of all countries
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Brunei', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Eswatini', code: 'SZ' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Greece', code: 'GR' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Ivory Coast', code: 'CI' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'Kosovo', code: 'XK' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: 'Laos', code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macau', code: 'MO' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia', code: 'FM' },
  { name: 'Moldova', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'North Korea', code: 'KP' },
  { name: 'North Macedonia', code: 'MK' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestine', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russia', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'São Tomé and Príncipe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Korea', code: 'KR' },
  { name: 'South Sudan', code: 'SS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syria', code: 'SY' },
  { name: 'Taiwan', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Vatican City', code: 'VA' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

export const venueTypes = [
  { id: 'restaurant', label: 'Restaurant', icon: '🍽️' },
  { id: 'bar', label: 'Bar', icon: '🍺' },
  { id: 'nightclub', label: 'Nightclub', icon: '🪩' },
  { id: 'cafe', label: 'Cafe', icon: '☕' },
  { id: 'lounge', label: 'Lounge', icon: '🛋️' },
  { id: 'pub', label: 'Pub', icon: '🍻' },
  { id: 'food_truck', label: 'Food Truck', icon: '🚚' },
  { id: 'street_vendor', label: 'Street Vendor / Stall', icon: '🏪' },
  { id: 'pop_up', label: 'Pop-up Shop', icon: '⛺' },
  { id: 'concert_hall', label: 'Concert Hall / Venue', icon: '🎵' },
  { id: 'sports_bar', label: 'Sports Bar', icon: '🏈' },
  { id: 'brewery', label: 'Brewery / Taproom', icon: '🍺' },
  { id: 'winery', label: 'Winery', icon: '🍷' },
  { id: 'bakery', label: 'Bakery', icon: '🥐' },
  { id: 'fast_food', label: 'Fast Food', icon: '🍔' },
  { id: 'fine_dining', label: 'Fine Dining', icon: '🥂' },
  { id: 'hotel_bar', label: 'Hotel Bar/Restaurant', icon: '🏨' },
  { id: 'rooftop', label: 'Rooftop Bar', icon: '🌆' },
  { id: 'other', label: 'Other', icon: '📍' },
];

export const staffSizeOptions = [
  { id: 'solo', label: 'Just me (Solo)', description: 'One person operation' },
  { id: 'micro', label: '2-5 staff', description: 'Small family or team' },
  { id: 'small', label: '6-15 staff', description: 'Small business' },
  { id: 'medium', label: '16-50 staff', description: 'Medium sized venue' },
  { id: 'large', label: '51-100 staff', description: 'Large venue' },
  { id: 'enterprise', label: '100+ staff', description: 'Enterprise / Chain' },
];
